### ISSUE TITLE
Find new hosting

### ISSUE THREAD

**Issue by ryanj** [ryanj/gist-reveal#68]
Find a new hosting solution?

**Comment by Rob-Rychs** [comment]
+1 for gh-pages
https://medium.freecodecamp.org/hosting-on-github-pages-with-git-submodules-36815856c3f1
could you use this projects gists storage +with gh-pages for hosting?

**Comment by ryanj** [comment]
I'm interested in a fully client-side "Export to gh-pages" option, but you'd lose the ability to dynamically load content from a gist (zero deploy to update).

In order to avoid leaking API keys, the site would probably need to be re-generated on-change whenever relevant gist-IDs are modified.  

Currently, the service is being built on DockerHub and is being deployed to GKE.  Any nodejs hosting service should work, but I'd prefer to run it on a service that provides access to Kubernetes (for demo and learning purposes)

**Comment by Rob-Rychs** [comment]
> I'm interested in a fully client-side "Export to gh-pages" option, but you'd lose the ability to dynamically load content from a gist (zero deploy to update)

ahhh I understand better how this gist magic all works now. that'd be a really cool option to have but sounds like a lot of work to get it done right

> Currently, the service is being built on DockerHub and is being deployed to GKE. Any nodejs hosting service should work, but I'd prefer to run it on a service that provides access to Kubernetes (for demo and learning purposes)

That's actually what first drew me to your project beyond just reveal-js, as I would like to learn more re: DOCKER + Kubernetes

**Comment by ryanj** [comment]
currently running on DigitalOcean
