### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by pascalbe-dev** [ryanj/gist-reveal#85]
Hey, I saw your lightning talk about that tool and it looked super awesome and I wanted to try it out. Thanks for putting that together.

However, the URL of the website (http://gist-reveal.it/) is not accessible (timeout).

Is this project still maintained and usable?

**Comment by ryanj** [comment]
Sorry for the delay on this issue.  The site should be back up now.  

I'm planning on keeping it running long term, but am considering reimplementing the source code in another language
